# Site settings
title: "Alfredo Hernández"
description: "The personal site for Alfredo Hernández"

exclude: [vendor]

# Build settings
markdown:   kramdown
sass:
  sass_dir: assets/_sass
  style:    compressed
permalink:  /:title/

# Page settings
about_avatar:               "true"
about_name:                 "Alfredo Hernández"
about_title:                "Physicist and Open Source enthusiast."
about_subtitle:             "asd."
about_contact_email:        "aldomann.designs@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the cv_looking_for_work option entirely
# to leave blank
about_looking_for_work:     "yes"

# Decide which sections to use
# comment out to hide
cv_section_experience:      true
cv_section_education:       true
cv_section_conferences:     true
cv_section_certificates:    true
cv_section_projects:        false
cv_section_skills:          true
cv_section_misc:            true
cv_section_links:           false
cv_section_associations:    false

# Design settings
cv_theme:                   default
